# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e72ad54feb36847c8dcaf1af27bdee036192bb4682533965bc33f666609cf7a59c72f1aaffe273ca89408801b4275d9ab26547a6441daecb94eab3b887946cc

test:
  secret_key_base: 8a896b236df4c86f55f42005c71e9601554ad67cb319b3335f067e380f40fc747af1c7054c80e4277d9fea153490a394b412a79e08b01eb90d68b364e2c0159e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
